"""Initial migration

Revision ID: 239fb64e0810
Revises: 
Create Date: 2026-09-08 17:06:54.347343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239fb64e0810'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squadron_id', sa.String(length=50), nullable=False),
    sa.Column('winch_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('finish_day', 'di', 'sign_on'), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('left_drum', sa.Integer(), nullable=True),
    sa.Column('right_drum', sa.Integer(), nullable=True),
    sa.Column('operator_sn', sa.String(length=20), nullable=False),
    sa.Column('trainee', sa.String(length=20), nullable=True),
    sa.Column('cable_check', sa.String(length=20), nullable=True),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('launches',
    sa.Column('launch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('launch_number', sa.Integer(), nullable=True),
    sa.Column('squadron_id', sa.String(length=50), nullable=False),
    sa.Column('winch_id', sa.Integer(), nullable=False),
    sa.Column('drum', sa.Enum('left', 'right'), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('operator_sn', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('launch_id'),
    sa.UniqueConstraint('winch_id', 'drum', 'launch_number', name='uix_winch_drum_launch_number')
    )
    op.create_table('operators',
    sa.Column('service_no', sa.String(length=20), nullable=False),
    sa.Column('entra_oid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('squadron_id', sa.String(length=50), nullable=False),
    sa.Column('qualification_level', sa.Enum('trainee', 'operator', 'instructor', 'examiner'), nullable=False),
    sa.PrimaryKeyConstraint('service_no'),
    sa.UniqueConstraint('entra_oid')
    )
    op.create_table('squadrons',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('winches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=50), nullable=False),
    sa.Column('squadron_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winches')
    op.drop_table('squadrons')
    op.drop_table('operators')
    op.drop_table('launches')
    op.drop_table('day_log')
    # ### end Alembic commands ###
