"""Add foreign keys

Revision ID: 35db14d67d0e
Revises: 239fb64e0810
Create Date: 2026-09-08 17:31:05.269006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35db14d67d0e'
down_revision: Union[str, None] = '239fb64e0810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'day_log', 'operators', ['operator_sn'], ['service_no'])
    op.create_foreign_key(None, 'day_log', 'winches', ['winch_id'], ['id'])
    op.create_foreign_key(None, 'day_log', 'squadrons', ['squadron_id'], ['id'])
    op.create_foreign_key(None, 'launches', 'operators', ['operator_sn'], ['service_no'])
    op.create_foreign_key(None, 'launches', 'squadrons', ['squadron_id'], ['id'])
    op.create_foreign_key(None, 'launches', 'winches', ['winch_id'], ['id'])
    op.create_foreign_key(None, 'operators', 'squadrons', ['squadron_id'], ['id'])
    op.create_foreign_key(None, 'winches', 'squadrons', ['squadron_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'winches', type_='foreignkey')
    op.drop_constraint(None, 'operators', type_='foreignkey')
    op.drop_constraint(None, 'launches', type_='foreignkey')
    op.drop_constraint(None, 'launches', type_='foreignkey')
    op.drop_constraint(None, 'launches', type_='foreignkey')
    op.drop_constraint(None, 'day_log', type_='foreignkey')
    op.drop_constraint(None, 'day_log', type_='foreignkey')
    op.drop_constraint(None, 'day_log', type_='foreignkey')
    # ### end Alembic commands ###
